CREATE TABLE User (
    UserId INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(10),
    MailAddress VARCHAR(10),
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LoreId INT(10)
);
